apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000         # Port accessible inside the cluster
      targetPort: 3000    # Port on the Pod
      nodePort: 30007   # Port exposed on each node (can be in the range 30000-32767)
